Branch reservation app
haruki1227041209/Reservation_App pull request #1
Opened 2023-06-13 21:28 UTC by haruki1227041209

基礎が足りていなかったので多くの部分でつまづきましたが、色々と知識が増えてよかったです。
ただ、まだまだ理解しきれていない分が多いのでアドバイス多めにお願いします。

・confirmの実装は力づくでやった感じがあるのですが他にもありますか？
・レビュワーの方が実際にこれを作っていくとなったらどういう流れで作っていくのでしょうか？
（どのモデルからだったり、コントローラからかhtmlからかなど教えていただきたいです）

2023-06-14 05:59 UTC, haruki1227041209 commented
[routesの修正、バリデーションの修正]を修正しました。
よろしくお願いします。
再提出の時に質問があったら、ここに書けば良いですか？

2023-06-14 10:11 UTC, MasahiroMatsuno reviewed
![スクリーンショット 2023-06-14 19 10 41](https://github.com/haruki1227041209/Reservation_App/assets/64773002/bec5b085-1315-4a41-be93-86fde9d536ab)
宿の登録時にルーティングエラーが出ているようです。
rails db:migrate:resetを行って動作確認を一通りお願いたします！

また、質問に関しては質問ボックスにてお願い致します！

2023-06-14 10:11 UTC, MasahiroMatsuno commented on app/controllers/reservations_controller.rb
> +    p 'おはようおはようおはよう'
不要なコードは残さないようにしましょう！

2023-06-14 10:11 UTC, MasahiroMatsuno commented on config/routes.rb
> +  root 'rooms#index_toppage'
rootは先頭に書きましょう！

2023-06-14 10:57 UTC, haruki1227041209 commented
修正しました。
お願いします！

2023-06-17 02:43 UTC, yoji4910 requested changes
いくつかコメントしました
質問については回答してください

2023-06-17 02:43 UTC, yoji4910 commented on app/controllers/reservations_controller.rb
> +    end
[質問]
ここでは何をしていますか？
変数amountはどこで使っていますか？

2023-06-17 02:43 UTC, yoji4910 commented on app/views/reservations/confirm.html.erb
> +  <%= form_for @reservation, method: :post, url: confirm_user_room_reservations_path(user_id: @reservation.user_id, room_id: @reservation.room_id) do |form| %>
`form_with`を使いましょう

2023-06-17 03:53 UTC, haruki1227041209 commented on app/controllers/reservations_controller.rb
> +    end
ここでは何をしていますか？
各予約の宿泊料金を計算しています

変数amountはどこで使っていますか？
reservation.rbにpayment_amountメソッドを定義しているため不要でしたが、削除をし忘れていました。

2023-06-17 04:14 UTC, yoji4910 approved these changes
LGTM!

2023-06-29 18:27 UTC, merged